title: Michael Matloka
email: michal@matloka.com
tagline: Engineering software. Full stack.
description: Hey, I'm Michael. I'm a software engineer, and a person.
author:
    name: Michael Matloka
    twitter: MatlokaM
repository: Twixes/matloka.com
twitter:
    username: MatlokaM
    card: summary_large_image
image:
    path: /assets/banner.png
    height: 640
    width: 1280

date_format: '%-d %b %Y'

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-github-metadata

collections:
    posts:
        output: true
        permalink: /:title

defaults:
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: 'post'
