title: Michael Matloka
tagline: Software with a human touch.
description: Hey! I'm Michael. I'm a software engineer, and a person.
repository: Twixes/matloka.com
email: '%6D%69%63%68%61%6C%40%6D%61%74%6C%6F%6B%61%2E%63%6F%6D'
twitter:
    username: MatlokaM
    card: summary_large_image
logo: /assets/logo.png

date_format: '%-d %b %Y'

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-github-metadata

collections:
    posts:
        output: true
        permalink: /blog/:title

defaults:
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: 'post'
          author:
              name: Michael Matloka
              twitter: MatlokaM

kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: false
