title: Michael Matloka
tagline: Engineering software. Full stack.
description: Hey, I'm Michael. I'm a software engineer, and a person.
repository: Twixes/matloka.com
email: michael@matloka.com
twitter:
    username: MatlokaM
    card: summary_large_image
logo: /assets/logo.png

date_format: '%-d %b %Y'

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-github-metadata

collections:
    posts:
        output: true
        permalink: /blog/:title

defaults:
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: 'post'
          author:
              name: Michael Matloka
              twitter: MatlokaM

kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: false
